In [1]:
import pandas as pd

In [12]:
series1 = pd.Series([1,2,3,4,5])
print(series)
print(type(series))

# index
print(series[0])
print(series[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
4

In [16]:
series2 = pd.Series([23, 24, 25, 26], index=["Adam", "Eve", "Bob", "Charlie"])
print(series2)
print(series2["Bob"])

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
25

In [21]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,9,8,7,6])

s1+s2

s1[0] = 100
changed_s1 = s1.drop(0)

print(s1)
print(changed_s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [31]:
# Dataframe

info = {
    "Name": ["Ansh", "Nandani", "Shivam"],
    "Age": [20,19,21],
    "CGPA": [7.5, 9.5, 8.5],
}

df = pd.DataFrame(info)
print(type(df))
print(df.index)
print(df.columns)

<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='str')

In [32]:
df

      Name  Age  CGPA
0     Ansh   20   7.5
1  Nandani   19   9.5
2   Shivam   21   8.5

In [36]:
df2 = pd.DataFrame([["Ansh", 20], ["Nandani", 19], ["Shivam", 21]], columns=["Name", "Age"])

In [37]:
df2

      Name  Age
0     Ansh   20
1  Nandani   19
2   Shivam   21

In [41]:
import numpy as np

np_arr = np.array([[1,2,3], [4,5,6]])

df3 = pd.DataFrame(np_arr, columns=["A","B","C"])

In [42]:
df3

   A  B  C
0  1  2  3
1  4  5  6